[toolchain]
anchor_version = "0.32.1"
solana_version = "3.0.13"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
cascade = "DJQChB4riBobXMsFgJwa5wGpwXGzGsrv8EMsWkT6SGnB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run tsx --test --test-reporter=spec tests/*.ts"
