name: Continuous deployment
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pre-req
        run: |
          sudo apt-get install -y \
          build-essential \
          pkg-config \
          libudev-dev llvm libclang-dev \
          protobuf-compiler libssl-dev

      - name: Install rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Anchor
        run: |
          cargo install --git https://github.com/solana-foundation/anchor avm --force
          avm install latest
          avm use latest
          anchor build
          
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: web

      - uses: borales/actions-yarn@v4
        env:
          VITE_AW_ENDPOINT: https://fra.cloud.appwrite.io/v1
          VITE_AW_PROJECT_ID: 68d05ecf001fbe3f0133
          VITE_AW_DATABASE_ID: 68d06873001a2fae1d45
          VITE_PROGRAM_ID: HQ8ejrFMtoNsShZRqkH842BRDqpzh7Xy7b5iqc1U9ffA
          VITE_TREASURY_ID: 7hC5HoU81sjaFVaoGmM1bdKnSxbR6oWP1koBzKzBqKx8
        with:
          cmd: build
          dir: web
        
      - name: Build website
        run: | 
          cd web/
          touch ./dist/.nojekyll
          echo "whwhat.me" > ./dist/CNAME
          mv ./dist ../ 
    
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with: 
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Configure pages
        uses: actions/configure-pages@v5

      - name: Deploy to gh pages (whwhat.me)
        id: deployment
        uses: actions/deploy-pages@v4